# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\"\x1b\n\x0bTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\".\n\tTermReply\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xa0\x01\n\x08Glossary\x12#\n\x07GetTerm\x12\x0c.TermRequest\x1a\n.TermReply\x12!\n\x07\x41\x64\x64Term\x12\n.TermReply\x1a\n.TermReply\x12$\n\nUpdateTerm\x12\n.TermReply\x1a\n.TermReply\x12&\n\nDeleteTerm\x12\x0c.TermRequest\x1a\n.TermReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERMREQUEST']._serialized_start=18
  _globals['_TERMREQUEST']._serialized_end=45
  _globals['_TERMREPLY']._serialized_start=47
  _globals['_TERMREPLY']._serialized_end=93
  _globals['_GLOSSARY']._serialized_start=96
  _globals['_GLOSSARY']._serialized_end=256
# @@protoc_insertion_point(module_scope)
